name: ngrok-service
adopt-info: ngrok-service
summary: ngrok as a daemon
description: |
  ngrok as a service
base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  ngrok-service:
    plugin: dump
    source:
      - on amd64: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      - on arm64: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm64.zip
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(./ngrok --version | cut -d " " -f 3)
plugs:
  ngrok-config:
    interface: personal-files
    write:
      - $HOME/.ngrok2
apps:
  http:
    command: /snap/ngrok/28/ngrok start -config=/home/kusanagi2501/.ngrok2/ngrok.yml app-http
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, home, ngrok-config]
  https:
    command: /snap/ngrok/28/ngrok start -config=/home/kusanagi2501/.ngrok2/ngrok.yml app-https
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, home, ngrok-config]
